services:
########## NGINX ##########
  nginx:
    build:
      context: ${NGINX_CONTAINER_PATH}
    volumes:
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${NGINX_LOGS_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    links:
      - php-fpm

########## PHP-FPM ##########
  php-fpm:
    build:
      context: ${PHP_FPM_CONTAINER_PATH}
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${PHP_FPM_CONTAINER_PATH}/php.ini:/usr/local/etc/php/php.ini
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}

########## WORKSPACE ##########
  workspace:
    build:
      context: ${WORKSPACE_CONTAINER_PATH}
      args:
        - PHP_VERSION=${PHP_VERSION}
        - TZ=${WORKSPACE_TIMEZONE}
        - PUNAME=${WORKSPACE_NONROOT_USER_NAME}
        - PUID=${WORKSPACE_NONROOT_USER_ID}
        - PGNAME=${WORKSPACE_NONROOT_GROUP_NAME}
        - PGID=${WORKSPACE_NONROOT_GROUP_ID}
    volumes:
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
    tty: true

########## POSTGRES ##########
  postgres:
    image: postgis/postgis:latest
    volumes:
      - ${POSTGRES_CONTAINER_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

########## PGADMIN ##########
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ${PGADMIN_CONTAINER_PATH}/pgadmin:/var/lib/pgadmin

########## GEOSERVER ##########
  geoserver:
    image: kartoza/geoserver:${GEOSERVER_VERSION}
    ports:
        - ${GEOSERVER_PORT}:8080
    volumes:
      - ${GEOSERVER_CONTAINER_PATH}:${GEOSERVER_DATA_DIR}
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=${GEOSERVER_INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${GEOSERVER_MAXIMUM_MEMORY}