services:
  nginx:
    build:
      context: ${NGINX_CONTAINER_PATH}
    volumes:
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${NGINX_LOGS_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    links:
      - php-fpm

  php-fpm:
    build:
      context: ${PHP_FPM_CONTAINER_PATH}
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${PHP_FPM_CONTAINER_PATH}/php.ini:/usr/local/etc/php/php.ini
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
